### PR TITLE
DataSets search stack

### PR DESCRIPTION
**Pull request by c42f**
`dataset(name)` now searches for the first occurrence of `name` within a set of projects in a dataset search stack.

The stack can be initialized using patterns in the JULIA_DATASETS_PATH environment variable, which works somewhat similarly to JULIA_LOAD_PATH:

 - `@` means the path of the current active project as returned by
   `Base.active_project(false)` This can be useful when you're "doing
   scripting" and you've got a project-specific Data.toml which resides
   next to the Project.toml. This only applies to projects which are explicitly
   set with `julia --project` or `Pkg.activate()`.
 - Explicit paths may be either directories or files in Data.toml format.
   For directories, the filename "Data.toml" is implicitly appended.
 - As in DEPOT_PATH, an *empty* path component means the user's default
   Julia home directory, `joinpath(homedir(), ".julia", "datasets")`

All these paths are used to refer to data projects on the local disk in the Data.toml format.
If these local files are updated, this will be reflected dynamically in updating the associated
project in the stack.

This simplified version of the code loading rules (LOAD_PATH/DEPOT_PATH) is
used as it seems unlikely that we'll want data location to be julia-version-dependent
in the same way that that code is. (So there's no need for the `#` expansion.)

Unlike `LOAD_PATH`, `JULIA_DATASETS_PATH` is expanded inside the program as
a stack of `AbstractDataProject`. This is to allow other arbitrarily programmable data
projects to be added at runtime as necessary.  For example, fetching a list of datasets
from a server rather than from a local file.

### TODO
* [ ] Docs
* [x] Tests

### CODE REVIEW

**Comment by c42f** [comment]
@pfitzseb it would be great if you could have a look at the general design here. (Happy for any detailed code review too, though there's still some code cleanup and tests to fix/write).

I'm hoping this will help a lot with the interactivity we want on JuliaHub; to have availability of the user's datasets dynamically up to date and to deal with refreshing any authentication info.

**Comment by pfitzseb** [comment]
I feel like this design makes a lot of sense (keeping the FS in sync with any Data.toml updates is really nice to have). The actual update code (in JuliaHub) might be a bit tricky though; we'll need to decide how to trigger Data.toml updates etc (in general I'm not sure what happens when you e.g. delete a dataset while it's used by a job).

**Comment by c42f** [comment]
Thanks for having a look :+1:

> we'll need to decide how to trigger Data.toml updates etc

For the cluster I was imagining Data.toml be updated via the kubernetes secrets mechanism. Then the auto-update code here should just work (mainly this would apply to interactive jobs).

For usage outside the cluster we can have our own JuliaHub-specific `AbstractDataProject` (perhaps installed when the user loads JuliaHubClient) which isn't backed by a local Data.toml file, but by the JuliaHub API.

> what happens when you e.g. delete a dataset while it's used by a job

I think the best thing here would be to just let the job fail. Providing a clear error message is the tricky part. It could probably be done by modifying the S3 access policy used by the job which will then cause a permission error we can catch.

**Comment by c42f** [comment]
I've added tests and reworked the API a bunch so I think this is basically ready.

Looks like there's a test or two to fix on windows.

**Pull request merged**
